const engines = {
    "Brave": "https://search.brave.com/search?q=%s",
    "DuckDuckGo": "https://duckduckgo.com/?q=%s",
    "Google": "https://www.google.com/search?q=%s",
    "Bing": "https://www.bing.com/search?q=%s",
    "Ecosia": "https://www.ecosia.org/search?q=%s",
    "Duden": "https://www.duden.de/suchen/dudenonline/%s",
    "GitHub": "https://github.com/search?q=%s",
    "Qwant": "https://www.qwant.com/?q=%s",
    "Reddit": "https://www.reddit.com/search/?q=%s",
    "Spotify": "https://open.spotify.com/search/%s",
    "Wikipedia": "https://de.wikipedia.org/w/index.php?go=Go&search=%s",
    "Youtube": "https://www.youtube.com/results?search_query=%s",
    "Openstreetmap": "https://www.openstreetmap.org/search?query=%s",
    "Amazon": "https://www.amazon.de/s?k=%s",
    "Startpage": "https://www.startpage.com/sp/search?query=%s",
    "MDN": "https://developer.mozilla.org/en-US/search?q=%s",
    "ebay": "https://www.ebay-kleinanzeigen.de/s-%s/k0",
    "YouTube Music": "https://music.youtube.com/search?q=%s",
    "Twitch": "https://www.twitch.tv/search?term=%s",
    "ARD": "https://www.ardmediathek.de/suche/%s",
    "ZDF": "https://www.zdf.de/suche?q=%s",
    "DeepL": "https://www.deepl.com/translator#en/de/%s"
}